[platformio]
src_dir = .
default_envs = console_esp32

[env]
monitor_speed = 115200
build_flags =
  -I shared/include

[env:console_esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter =
  -<*>
  +<firmware/console-esp32/src/>

[env:pad_esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter =
  -<*>
  +<firmware/pad-esp32/src/>

[env:console_rp2040_ps]
platform = raspberrypi
board = seeed_xiao_rp2040
framework = arduino
lib_deps =
  adafruit/Adafruit TinyUSB Library@^3.1.4
build_flags =
  ${env.build_flags}
  -DUSE_TINYUSB
build_src_filter =
  -<*>
  +<firmware/console-rp2040/src/>

[env:console_rp2040_xbox360]
platform = raspberrypi
board = seeed_xiao_rp2040
framework = arduino
lib_deps =
  adafruit/Adafruit TinyUSB Library@^3.1.4
build_flags =
  ${env.build_flags}
  -DUSE_TINYUSB
  -DTOY_PROFILE_XBOX360
build_src_filter =
  -<*>
  +<firmware/console-rp2040/src/>