; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#v1.4.0-gcc14-arduinopico460
board = seeed_xiao_rp2040
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5MB
monitor_speed = 115200
lib_deps =
	adafruit/Adafruit TinyUSB Library@3.1.4
	adafruit/Adafruit NeoPixel@^1.12.0
lib_ignore = 
	SdFat - Adafruit Fork
	Adafruit SPIFlash
	MIDI Library
extra_scripts =
	../../tools/set_version_flag.py
	pre:extra_script.py
build_flags = 
	-I ../../shared/include
	-DUSE_TINYUSB
	-DFW_TARGET='"console-rp2040"'
	-DUSB_VID=0x0E6F
	-DUSB_PID=0x0241
	-Wl,--wrap=TinyUSB_Device_Init
	-Wl,--wrap=tud_descriptor_configuration_cb
	-Wl,--wrap=tud_descriptor_string_cb
	-DCFG_TUD_HID_EP_BUFSIZE=32
	-DCFG_TUD_VENDOR=1

[env:console_rp2040]
