; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
lib_deps = adafruit/Adafruit TinyUSB Library@3.1.4
lib_ignore = 
	SdFat - Adafruit Fork
	Adafruit SPIFlash
	MIDI Library
	Adafruit NeoPixel
build_flags = 
	-I ../../shared/include
	-DUSE_TINYUSB
	-DUSB_VID=0x0E6F
	-DUSB_PID=0x0241
	-Wl,--wrap=TinyUSB_Device_Init
	-Wl,--wrap=tud_descriptor_configuration_cb
	-DCFG_TUD_HID_EP_BUFSIZE=32

[env:console_rp2040]
